name: 'Publish Preview of Docs Site from branch'

# The publish_docs_preview.yml workflow takes a PR and publishes the results to it's own branch 
# so users can preview it.  But that git branch then needs some way to publish, so this action does that.

on: 
  push:
    branch:
        - gh-pages

permissions:
  pages: 'write'
  id-token: 'write'


jobs:
  stage:
    name: "Stage PR preview from branch to pages"
    runs-on: 'ubuntu-24.04'
    steps:
    - uses: 'actions/checkout@v4'
      with:
        ref: 'refs/heads/gh-pages'
    - name: 'Upload artifact'
      uses: 'actions/upload-pages-artifact@v3'
      with:
        path: '.'
  deploy:
    name: "Deploy PR Preview from branch to pages"
    needs: 'stage'
    environment:
      name: 'gh-pages-pr-preview'
      url: '${{ steps.deployment.outputs.page_url }}'
    runs-on: 'ubuntu-24.04'
    steps:
      - name: 'Deploy to GitHub Pages'
        id: 'deployment'
        uses: 'actions/deploy-pages@v4'
