### Ensure that Yaml files are properly formatted
name: 'Check Yaml Format'
on:
  pull_request:
    paths:
      - '**.yml'
      - '**.yaml'
jobs:
  yamlfmt:
    name: 'yamlfmt'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout Code'
        uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683' # ratchet:actions/checkout@v4
      - name: 'Check Yaml Format'
        run: 'tools/yamlfmt --lint .'
